version: '3.8'

services:
  php:
    build:
      context: docker/dockerfiles
      dockerfile: Php8Docker
      args:
        - DOCKER_USERNAME=${USERNAME}
        - DOCKER_UID=${USERID}
    env_file:
      - .env
    volumes:
      - ./src:/var/www
      - ./docker/php-ini:/usr/local/etc/php
      - ./docker/xdebug-ini/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/sampler:/usr/local/etc/sampler
    container_name: ${CONTAINER_NAME_API}
    restart: unless-stopped
    networks:
      - DevEnvNetwork
    tty: true
    stdin_open: true
    links:
      - mysql:database
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
    depends_on:
      - mysql

  nginx:
    build:
      context: docker/dockerfiles
      dockerfile: NginxDocker
    container_name: ${CONTAINER_NAME_NGINX}
    networks:
      - DevEnvNetwork
    links:
      - mysql:database
    ports:
      - ${HOST}:${HTTP_PORT}:80
    volumes:
      - ./docker/sites:/etc/nginx/conf.d
      - ./src:/var/www
    depends_on:
      - php

  mysql:
    build:
      context: docker/dockerfiles
      dockerfile: MysqlDocker
    container_name: ${CONTAINER_NAME_MYSQL}
    networks:
      - DevEnvNetwork
    ports:
      - ${HOST}:${MYSQL_PORT}:3306
    volumes:
      - ./docker/mysql:/etc/mysql/conf.d
      - ./docker/databases:/var/databases
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DEFAULT_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}


networks:
  DevEnvNetwork:
    name: DevEnvNetwork
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16
